### ISSUE TITLE
enquiry about the outdoor dataset

### ISSUE THREAD

**Issue by Mahmoudadham4040** [ebhrz/HDMap#1]
I attempted to download the outdoor dataset, but the full gigabytes of data did not successfully downloaded (only 45g from 64.5g)

**Comment by ebhrz** [comment]
It's kind of strange, because the file is on the dropbox cloud. Could you try again and check if it is OK? If the error still occur, I can share you a new copy link.

**Comment by Mahmoudadham4040** [comment]
Thank you for your reply. i attempted from 4 different devices many times but the same issue.

**Comment by Mahmoudadham4040** [comment]
The content of the downloaded part of the outdoor.bag is different from the the description in your GitHub page as attached (in addition to the problem of not full downloaded)
"
path:        2023-01-31 - Outdoor.bag
version:     2.0
duration:    24:03s (1443s)
start:       Dec 23 2021 11:43:52.57 (1640231032.57)
end:         Dec 23 2021 12:07:56.40 (1640232476.40)
size:        45.1 GB
messages:    83243
compression: none [28854/28854 chunks]
types:       sensor_msgs/CompressedImage [8f7a12909da2c9d3332d540a0977563f]
             sensor_msgs/PointCloud2     [1158d486dd51d683ce2f1be655c3c181]
topics:      /dedistortion_cloud   14427 msgs    : sensor_msgs/PointCloud2    
             /image                39963 msgs    : sensor_msgs/CompressedImage
             /origin_cloud         28853 msgs    : sensor_msgs/PointCloud2
"

**Comment by ebhrz** [comment]
Hi, I just upload another copy, could you try this link?

https://www.dropbox.com/scl/fi/3dot1wa8t1aoaf4fgim4n/fix_hd_undistortion.bag?rlkey=0pcu62o3ofkza4cs8nih06p9m&dl=0

**Comment by Mahmoudadham4040** [comment]
> Hi, I just upload another copy, could you try this link?
> 
> https://www.dropbox.com/scl/fi/3dot1wa8t1aoaf4fgim4n/fix_hd_undistortion.bag?rlkey=0pcu62o3ofkza4cs8nih06p9m&dl=0

still same error,  are you attempted to download this data?

**Comment by ebhrz** [comment]
Hi, I've tried with my colleagues, and reproduce the issue. It seems the problem from dropbox. I'll split it to two files, and reupload. Sorry for the issue, I'll tell you when it was done.

**Comment by Mahmoudadham4040** [comment]
> Hi, I've tried with my colleagues, and reproduce the issue. It seems the problem from dropbox. I'll split it to two files, and reupload. Sorry for the issue, I'll tell you when it was done.
are there any updates about the dataset?

**Comment by ebhrz** [comment]
Hi, I use split command to split it to three files, you can download and use command `cat outdoor.bag.part1 outdoor.bag.part2 outdoor.bag.part3 > outdoor.bag` to merge them. the md5 of the original file is 73347544b80d2bd6f07e29d628af30e4,
the link is at: https://www.dropbox.com/scl/fo/lpa2gqalu5ide6wk9xc9q/ACGrRd6f70YR2pfgA_oaWM4?rlkey=19z3m24hov2ho9x6acn8ho9y6&st=ijk89n3e&dl=0

**Comment by Mahmoudadham4040** [comment]
s there an issue with running the command python3 vector.py -c config/vector_config.json in the outdoor example? It appears that the files vector.py and config/vector_config.json are missing

**Comment by ebhrz** [comment]
just try outdoor_config.json

**Comment by Oliverbihop** [comment]
I also had the same problem with the indoor bag file. Could you please help me to check it? File is always 38GB instead of 70GB

**Comment by ebhrz** [comment]
> I also had the same problem with the indoor bag file. Could you please help me to check it? File is always 38GB instead of 70GB

Hi @Oliverbihop , have you tried the above link and unzip method?

> Hi, I use split command to split it to three files, you can download and use command `cat outdoor.bag.part1 outdoor.bag.part2 outdoor.bag.part3 > outdoor.bag` to merge them. the md5 of the original file is 73347544b80d2bd6f07e29d628af30e4, the link is at: https://www.dropbox.com/scl/fo/lpa2gqalu5ide6wk9xc9q/ACGrRd6f70YR2pfgA_oaWM4?rlkey=19z3m24hov2ho9x6acn8ho9y6&st=ijk89n3e&dl=0

**Comment by Oliverbihop** [comment]
Thanks for your reply. Yes, I did try, and it works with the outdoor bag file (cat from 3 given files), but I still want to test with the indoor settings.  Could you provide the same method for the indoor bag file?

**Comment by ebhrz** [comment]
> Thanks for your reply. Yes, I did try, and it works with the outdoor bag file (cat from 3 given files), but I still want to test with the indoor settings. Could you provide the same method for the indoor bag file?

Sorry for my misunderstanding, I've uploaded indoor bag into the same folder, you can check them out and also use:
```
cat indoor.bag.part1 indoor.bag.part2 indoor.bag.part3 > indoor.bag
```
https://www.dropbox.com/scl/fo/lpa2gqalu5ide6wk9xc9q/ACGrRd6f70YR2pfgA_oaWM4?rlkey=19z3m24hov2ho9x6acn8ho9y6&st=x63w5qyd&dl=0

**Comment by Oliverbihop** [comment]
Thank you very much.

**Comment by GPrathap** [comment]
Hi @ebhrz 

root@07b23a1a9fdc:~/HDMap/data/outdoor# rosbag info outdoor.bag      
path:        outdoor.bag
version:     2.0
duration:    33:57s (2037s)
start:       Dec 23 2021 03:43:52.57 (1640231032.57)
end:         Dec 23 2021 04:17:50.01 (1640233070.01)
size:        63.3 GB
messages:    117677
compression: none [40714/40714 chunks]
types:       sensor_msgs/CompressedImage [8f7a12909da2c9d3332d540a0977563f]
             sensor_msgs/PointCloud2     [1158d486dd51d683ce2f1be655c3c181]
topics:      /dedistortion_cloud   20356 msgs    : sensor_msgs/PointCloud2    
             /image                56609 msgs    : sensor_msgs/CompressedImage
             /origin_cloud         40712 msgs    : sensor_msgs/PointCloud2


seems to be bag files does not inlcude gnss topic ( 

Can you have a look?

**Comment by ebhrz** [comment]
> Hi [@ebhrz](https://github.com/ebhrz)
> 
> root@07b23a1a9fdc:~/HDMap/data/outdoor# rosbag info outdoor.bag path: outdoor.bag version: 2.0 duration: 33:57s (2037s) start: Dec 23 2021 03:43:52.57 (1640231032.57) end: Dec 23 2021 04:17:50.01 (1640233070.01) size: 63.3 GB messages: 117677 compression: none [40714/40714 chunks] types: sensor_msgs/CompressedImage [8f7a12909da2c9d3332d540a0977563f] sensor_msgs/PointCloud2 [1158d486dd51d683ce2f1be655c3c181] topics: /dedistortion_cloud 20356 msgs : sensor_msgs/PointCloud2 /image 56609 msgs : sensor_msgs/CompressedImage /origin_cloud 40712 msgs : sensor_msgs/PointCloud2
> 
> seems to be bag files does not inlcude gnss topic (
> 
> Can you have a look?

It seems you also used the broken bag. Did you get the bag by combining the three parts? Please check the MD5 "73347544b80d2bd6f07e29d628af30e4".

**Comment by GPrathap** [comment]
Hi @ebhrz , this is what I get 0ccdb4ac43e6ea01b9ba79d68b233faa (

**Comment by ebhrz** [comment]
@GPrathap This is not correct. Do you use this command to splice the data?
```
cat indoor.bag.part1 indoor.bag.part2 indoor.bag.part3 > indoor.bag
```
